/attendance/manage.do=attendance.command.AttendanceManagementHandler
/attendance/list.do=attendance.command.AttendanceListHandler
/attendance/delete.do=attendance.command.AttendanceDeleteHandler
/attendance/monthly.do=attendance.command.MonthlyAttendanceHandler
/attendance/detail.do=employee.command.AttendanceDetailHandler
/attendance/save.do=attendance.command.AttendanceSaveHandler
/vacationTypeSetting.do=vacation.command.VacationTypeSettingHandler
/vacationTypeSave.do=vacation.command.VacationTypeSaveHandler
/vacationTypeUpdate.do=vacation.command.VacationTypeUpdateHandler
/vacationTypeDelete.do=vacation.command.VacationTypeDeleteHandler

/attendanceGroupManage.do=attendance.command.AttendanceGroupManageHandler
/attendanceGroupSave.do=attendance.command.AttendanceGroupSaveHandler
/attendanceGroupUpdate.do=attendance.command.AttendanceGroupUpdateHandler
/attendanceGroupDelete.do=attendance.command.AttendanceGroupDeleteHandler
/attendanceGroupReset.do=attendance.command.AttendanceGroupResetHandler

/attendanceTypeSave.do=attendance.command.AttendanceTypeSaveHandler
/attendanceTypeUpdate.do=attendance.command.AttendanceTypeUpdateHandler
/attendanceTypeDelete.do=attendance.command.AttendanceTypeDeleteHandler
/vacationDaysManage.do=vacation.command.VacationDaysManageHandler
#/vacationDaysDelete.do=vacation.command.VacationDaysDeleteHandler
#/vacationDaysAutoCalc.do

/wage/itemLedger.do=wage.command.WageItemLedgerHandler
/wage/ledger.do=wage.command.WageLedgerHandler
/wage/ledgerDetail.do=wage.command.WageLedgerDetailHandler
/wage/employeeHistory.do=wage.command.WageEmployeeHistoryHandler
/wage/insuranceDeduction.do=wage.command.WageInsuranceDeductionHandler

/wageTypeSetting.do=wage.command.WageTypeSettingHandler
/wageTypeSave.do=wage.command.WageTypeSaveHandler
/wageTypeUpdate.do=wage.command.WageTypeUpdateHandler
/wageTypeDelete.do=wage.command.WageTypeDeleteHandler

/wage/monthlyTotalStatistics.do=wage.command.WageMonthlyTotalStatisticsHandler
/wage/yearlyTotalStatistics.do=wage.command.WageYearlyTotalStatisticsHandler
/wage/monthlyPersonalStatistics.do=wage.command.WageMonthlyPersonalStatisticsHandler
/wage/yearlyPersonalStatistics.do=wage.command.WageYearlyPersonalStatisticsHandler
/wage/itemCompositionStatistics.do=wage.command.WageItemCompositionStatisticsHandler


/employee/register.do=employee.command.EmployeeRegisterHandler
/employee/register2.do=employee.command.EmployeeRegister2Handler
/employee/register2_process.do=employee.command.EmployeeRegister2ProcessHandler

/wage/paymentInput.do=wage.command.WagePaymentInputHandler
/wage/paymentInputCalculate.do=wage.command.WagePaymentInputCalculateHandler
/wage/paymentInputSave.do=wage.command.WagePaymentInputSaveHandler
/wage/paymentPreviousCopy.do=wage.command.WagePaymentPreviousCopyHandler
/wage/paymentInputDelete.do=wage.command.WagePaymentInputDeleteHandler
/wage/dailyPaymentInput.do=wage.command.DailyWagePaymentInputHandler
/wage/dailyPaymentInputCalculate.do=wage.command.DailyWagePaymentInputCalculateHandler
/wage/dailyPaymentInputSave.do=wage.command.DailyWagePaymentInputSaveHandler
/wage/dailyPaymentInputDelete.do=wage.command.DailyWagePaymentInputDeleteHandler

/dailywork/manage.do=dailywork.command.DailyWorkManageHandler
/dailywork/save.do=dailywork.command.DailyWorkSaveHandler
/dailywork/projectManage.do=dailywork.command.ProjectManageHandler
/dailywork/list.do=dailywork.command.DailyWorkListHandler
/dailywork/delete.do=dailywork.command.DailyWorkDeleteHandler
/dailywork/monthly.do=dailywork.command.DailyWorkMonthlyHandler
/dailywork/detail.do=dailywork.command.DailyWorkDetailHandler

