/vacationTypeSetting.do=vacation.command.VacationTypeSettingHandler
/vacationTypeSave.do=vacation.command.VacationTypeSaveHandler
/vacationTypeUpdate.do=vacation.command.VacationTypeUpdateHandler
/vacationTypeDelete.do=vacation.command.VacationTypeDeleteHandler
/attendanceGroupManage.do=attendance.command.AttendanceGroupManageHandler
/attendanceGroupSave.do=attendance.command.AttendanceGroupSaveHandler
/attendanceGroupUpdate.do=attendance.command.AttendanceGroupUpdateHandler
/attendanceGroupDelete.do=attendance.command.AttendanceGroupDeleteHandler
/attendanceGroupReset.do=attendance.command.AttendanceGroupResetHandler